version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
    command: uvicorn app.app:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres:15.4
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file: .env

  web:
    build: .
    restart: unless-stopped
    image: cr.yandex/crp88vjqor38o85hoocl/chat-defender-web-ui
    container_name: web
    env_file:
      - ./.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot_proxy.rule=Host(`bank-system.by`)"
      - "traefik.http.routers.bot_proxy.entrypoints=websecure"
      - "traefik.http.routers.bot_proxy.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
      - "traefik.http.routers.bot_proxy.middlewares=auth@file,http_cat_errors@file"
  networks:
    web:
      external: true
