ersion: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
    command: uvicorn app.app:app --reload --host 0.0.0.0 --port 8000
      #    env_file:
      #- .env
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bot_proxy.rule=Host(`bot.prodigy.by`)"
      - "traefik.http.routers.bot_proxy.entrypoints=websecure"
      - "traefik.http.routers.bot_proxy.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
      - "traefik.http.routers.bot_proxy.middlewares=auth@file,http_cat_errors@file"
    networks:
      - web
  db:
    image: postgres:15.4
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
        # env_file: .env

volumes:
  db_volume:

networks:
  web:
    external: true